export const STATUS_CODES = Object.freeze({
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
});

export const ERROR_CODES = Object.freeze({
  AUTH_001: 'AUTH_001',
  AUTH_002: 'AUTH_002',
  AUTH_003: 'AUTH_003',
  AUTH_004: 'AUTH_004',
  AUTH_005: 'AUTH_005',
  RATE_001: 'RATE_001',
  VALIDATION_001: 'VALIDATION_001',
  VALIDATION_002: 'VALIDATION_002',
  VALIDATION_003: 'VALIDATION_003',
  PROXY_001: 'PROXY_001',
  PROXY_002: 'PROXY_002',
  PROXY_003: 'PROXY_003',
  PROXY_004: 'PROXY_004',
  PROXY_005: 'PROXY_005',
  GATEWAY_001: 'GATEWAY_001',
  GATEWAY_002: 'GATEWAY_002',
  GATEWAY_003: 'GATEWAY_003',
  GATEWAY_004: 'GATEWAY_004',
  POLICY_001: 'POLICY_001',
  POLICY_002: 'POLICY_002',
  POLICY_003: 'POLICY_003',
  INTERNAL_001: 'INTERNAL_001',
  INTERNAL_002: 'INTERNAL_002',
});

export const EVENTS = Object.freeze({
  REQUEST_RECEIVED: 'gateway:request:received',
  REQUEST_VALIDATED: 'gateway:request:validated',
  AUTH_STARTED: 'gateway:auth:started',
  AUTH_SUCCESS: 'gateway:auth:success',
  AUTH_FAILED: 'gateway:auth:failure',
  POLICY_STARTED: 'gateway:policy:started',
  POLICY_PASSED: 'gateway:policy:pass',
  POLICY_DENIED: 'gateway:policy:deny',
  PROXY_STARTED: 'gateway:proxy:start',
  PROXY_COMPLETED: 'gateway:proxy:end',
  PROXY_FAILED: 'gateway:proxy:error',
  REQUEST_COMPLETED: 'gateway:request:completed',
  PROXY_REQUEST_START: 'gateway:proxy:start',
  PROXY_REQUEST_END: 'gateway:proxy:end',
  PROXY_REQUEST_ERROR: 'gateway:proxy:error',
  PROXY_TIMEOUT: 'gateway:proxy:timeout',
  CIRCUIT_OPEN: 'gateway:circuit:open',
  CIRCUIT_HALF_OPEN: 'gateway:circuit:halfOpen',
  CIRCUIT_CLOSE: 'gateway:circuit:close',
  CIRCUIT_FALLBACK: 'gateway:circuit:fallback',
  RATE_LIMIT_HIT: 'gateway:rateLimit:hit',
  RATE_LIMIT_EXCEEDED: 'gateway:rateLimit:exceeded',
  SERVER_STARTING: 'gateway:server:starting',
  SERVER_READY: 'gateway:server:ready',
  SERVER_SHUTTING_DOWN: 'gateway:server:shuttingDown',
  SERVER_SHUTDOWN_COMPLETE: 'gateway:server:shutdownComplete',
  HEALTH_CHECK_START: 'gateway:health:start',
  HEALTH_CHECK_COMPLETE: 'gateway:health:complete',
  SERVICE_HEALTHY: 'gateway:service:healthy',
  SERVICE_UNHEALTHY: 'gateway:service:unhealthy',
});

export const MESSAGES = Object.freeze({
  SUCCESS: 'Request completed successfully.',
  CREATED: 'Resource created successfully.',
  UPDATED: 'Resource updated successfully.',
  DELETED: 'Resource deleted successfully.',
  AUTH_TOKEN_MISSING: 'Authentication token is required. Please provide a valid Bearer token.',
  AUTH_TOKEN_EXPIRED: 'Authentication token has expired. Please refresh your token.',
  AUTH_TOKEN_INVALID: 'Authentication token is invalid or malformed.',
  AUTH_SERVICE_UNAVAILABLE: 'Authentication service is temporarily unavailable. Please try again.',
  AUTH_INSUFFICIENT_PERMISSIONS: 'You do not have sufficient permissions to perform this action.',
  AUTH_LOGIN_SUCCESS: 'Login successful.',
  AUTH_LOGOUT_SUCCESS: 'Logout successful.',
  RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later.',
  VALIDATION_FAILED: 'Request validation failed. Please check your input.',
  INVALID_REQUEST_BODY: 'Request body is invalid or malformed.',
  MISSING_REQUIRED_FIELDS: 'One or more required fields are missing.',
  SERVICE_UNAVAILABLE: 'The requested service is temporarily unavailable. Please try again later.',
  UPSTREAM_TIMEOUT: 'The upstream service did not respond in time.',
  CIRCUIT_BREAKER_OPEN: 'Service is temporarily unavailable due to high error rate. Requests are being short-circuited.',
  BAD_GATEWAY: 'Received an invalid response from the upstream service.',
  GATEWAY_TIMEOUT: 'The gateway timed out while processing your request.',
  ROUTE_NOT_FOUND: 'The requested endpoint does not exist.',
  METHOD_NOT_ALLOWED: 'The HTTP method is not supported for this endpoint.',
  OWNERSHIP_VIOLATION: 'You can only access resources that belong to you.',
  ROLE_VIOLATION: 'Your role does not permit this action.',
  ACCESS_DENIED: 'Access to the requested resource has been denied.',
  INTERNAL_ERROR: 'An internal server error occurred. Please try again later.',
  SHUTTING_DOWN: 'Server is shutting down. Please retry your request.',
  HEALTH_OK: 'Gateway is healthy and all services are reachable.',
  HEALTH_DEGRADED: 'Gateway is operational but some downstream services are unreachable.',
  READY: 'Gateway is ready to accept traffic.',
  LIVE: 'Gateway process is alive.',
});

export const ROLES = Object.freeze({
  ADMIN: 'admin',
  RECRUITER: 'recruiter',
  CANDIDATE: 'candidate',
  SUPER_ADMIN: 'super_admin',
  GUEST: 'guest',
});

export const ROLE_HIERARCHY = Object.freeze([
  ROLES.GUEST,
  ROLES.CANDIDATE,
  ROLES.RECRUITER,
  ROLES.ADMIN,
  ROLES.SUPER_ADMIN,
]);

export const hasMinimumRole = (userRole, requiredRole) => {
  const userIndex = ROLE_HIERARCHY.indexOf(userRole);
  const requiredIndex = ROLE_HIERARCHY.indexOf(requiredRole);
  if (userIndex === -1 || requiredIndex === -1) return false;
  return userIndex >= requiredIndex;
};

export default {
  STATUS_CODES,
  ERROR_CODES,
  EVENTS,
  MESSAGES,
  ROLES,
  ROLE_HIERARCHY,
  hasMinimumRole,
};
