apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: hire1percent
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"
      otlp/jaeger:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true
      logging:
        verbosity: basic
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger, logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus, logging]
