import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
    Brain,
    CheckCircle,
    Play,
    AlertCircle,
    Clock,
    XCircle,
    ArrowRight,
    ArrowLeft,
    Code,
    List
} from 'lucide-react';
import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

const SkillAssessment = ({ job, user, onComplete, onBack }) => {
    const [started, setStarted] = useState(false);
    const [loading, setLoading] = useState(false);
    const [questions, setQuestions] = useState([]);
    const [currentQIndex, setCurrentQIndex] = useState(0);
    const [answers, setAnswers] = useState({});
    const [score, setScore] = useState(null);
    const [error, setError] = useState(null);

    /* ===========================
       START ASSESSMENT
       =========================== */
    const startAssessment = async () => {
        setLoading(true);
        setError(null);

        try {
            const res = await axios.post(
                `${API_BASE_URL}/api/generate-full-assessment`,
                {
                    jobId: job._id,
                    userId: user.uid
                }
            );

            console.log("[FRONTEND] Received:", res.data);

            if (!Array.isArray(res.data?.questions) || res.data.questions.length === 0) {
                throw new Error('No questions in response');
            }

            setQuestions(res.data.questions);
            setStarted(true);
        } catch (err) {
            console.error("Start Assessment Failed:", err);
            setError(
                err.response?.data?.message ||
                err.message ||
                'Failed to generate assessment. Please try again.'
            );
        } finally {
            setLoading(false);
        }
    };

    /* ===========================
       ANSWER HANDLING
       =========================== */
    const handleAnswer = (value) => {
        setAnswers(prev => ({ ...prev, [currentQIndex]: value }));
    };

    const nextQuestion = () => {
        if (currentQIndex < questions.length - 1) {
            setCurrentQIndex(i => i + 1);
        } else {
            finishAssessment();
        }
    };

    /* ===========================
       FINISH & SCORE
       =========================== */
    const finishAssessment = async () => {
        let correct = 0;

        questions.forEach((q, idx) => {
            const userAns = answers[idx];

            if (q.type === 'mcq') {
                if (q.options[q.correctAnswer] === userAns) {
                    correct++;
                }
            } else if (q.type === 'coding') {
                // Simple heuristic
                if (userAns && userAns.trim().length > 20) {
                    correct++;
                }
            }
        });

        const finalScore = Math.round((correct / questions.length) * 100);
        setScore(finalScore);

        try {
            await axios.post(`${API_BASE_URL}/api/applications`, {
                jobId: job._id,
                userId: user.uid,
                assessmentScore: finalScore
            });
        } catch (e) {
            console.warn('Score save failed (soft-fail)');
        }
    };

    const PASS_THRESHOLD = job.minPercentage || 60;
    const isPassed = score !== null && score >= PASS_THRESHOLD;

    /* ===========================
       LOADING UI
       =========================== */
    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center py-32">
                <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-indigo-600 mb-6"></div>
                <h3 className="text-xl font-bold">Generating Skill Assessment</h3>
                <p className="text-gray-500 mt-2">
                    AI is creating {job.assessment?.totalQuestions || 5} unique questions
                </p>
            </div>
        );
    }

    /* ===========================
       START SCREEN
       =========================== */
    if (!started && score === null) {
        return (
            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="max-w-2xl mx-auto bg-white rounded-3xl shadow-xl p-10 text-center"
            >
                <Brain className="w-16 h-16 text-indigo-600 mx-auto mb-6" />
                <h2 className="text-3xl font-black mb-4">Skill Assessment</h2>

                <p className="text-gray-600 mb-6">
                    This assessment is dynamically generated by AI based on the recruiter’s requirements.
                </p>

                <div className="bg-gray-50 rounded-xl p-5 text-left mb-6">
                    <div className="flex items-center text-gray-700 mb-2">
                        <List className="w-5 h-5 mr-2 text-indigo-600" />
                        <span><strong>Type:</strong> {job.assessment?.type?.toUpperCase() || 'MCQ'}</span>
                    </div>
                    <div className="flex items-center text-gray-700">
                        <Code className="w-5 h-5 mr-2 text-purple-600" />
                        <span><strong>Questions:</strong> {job.assessment?.totalQuestions || 5}</span>
                    </div>
                </div>

                {error && (
                    <div className="bg-red-50 text-red-600 p-4 rounded-xl mb-6">
                        {error}
                    </div>
                )}

                <div className="flex justify-center gap-4">
                    <button
                        onClick={onBack}
                        className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-8 py-4 rounded-xl font-bold text-lg flex items-center transition-colors"
                    >
                        <ArrowLeft className="mr-3 w-5 h-5" /> Back
                    </button>

                    <button
                        onClick={startAssessment}
                        className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-4 rounded-xl font-bold text-lg flex items-center shadow-lg hover:shadow-indigo-500/25 transition-all"
                    >
                        Start Assessment <Play className="ml-3 w-5 h-5" />
                    </button>
                </div>
            </motion.div>
        );
    }

    /* ===========================
       RESULT SCREEN
       =========================== */
    if (score !== null) {
        return (
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="max-w-3xl mx-auto bg-white rounded-3xl shadow-xl overflow-hidden text-center"
            >
                <div className="p-12 bg-green-600 text-white">
                    <CheckCircle className="w-20 h-20 mx-auto mb-4" />

                    <h2 className="text-3xl font-black mb-2">
                        Assessment Complete
                    </h2>

                    <div className="text-5xl font-black mt-4">{score}%</div>
                    <div className="opacity-80 mt-1">Score Captured</div>
                </div>

                <div className="p-8">
                    <button
                        onClick={() => onComplete(score)}
                        className="bg-indigo-600 text-white px-8 py-4 rounded-xl font-bold"
                    >
                        Proceed to Interview <ArrowRight className="inline ml-2" />
                    </button>
                </div>
            </motion.div>
        );
    }

    /* ===========================
       QUESTION VIEW — FIXED WITH SAFETY
       =========================== */
    // 🔥 Critical: Ensure we have valid question data
    if (questions.length === 0) {
        return (
            <div className="max-w-4xl mx-auto text-center py-20">
                <AlertCircle className="w-16 h-16 text-red-500 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-red-500">No questions loaded</h3>
                <p className="text-gray-600 mt-2">Please restart the assessment.</p>
                <button
                    onClick={onBack}
                    className="mt-6 bg-indigo-600 text-white px-6 py-3 rounded-xl"
                >
                    Go Back
                </button>
            </div>
        );
    }

    const q = questions[currentQIndex];

    // 🔒 Double-check q is valid
    if (!q || typeof q.question !== 'string') {
        console.warn(`[RENDER] Invalid question at index ${currentQIndex}`, q);
        return (
            <div className="max-w-4xl mx-auto text-center py-20">
                <AlertCircle className="w-16 h-16 text-orange-500 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-orange-600">Question data invalid</h3>
                <p className="text-gray-600 mt-2">Skipping to next...</p>
                <button
                    onClick={() => setCurrentQIndex(prev => Math.min(prev + 1, questions.length - 1))}
                    className="mt-6 bg-gray-600 text-white px-6 py-3 rounded-xl"
                >
                    Skip to Next
                </button>
            </div>
        );
    }

    return (
        <motion.div
            key={currentQIndex} // ✅ Critical: key prevents React from reusing old DOM nodes
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            className="max-w-4xl mx-auto"
        >
            <div className="bg-white rounded-3xl shadow-lg p-8">
                <div className="mb-6 flex justify-between">
                    <span className="text-sm font-bold text-indigo-600 uppercase">
                        {q.type === 'mcq' ? 'MCQ' : 'Coding'}
                    </span>
                    <span className="text-gray-400 font-bold">
                        {currentQIndex + 1}/{questions.length}
                    </span>
                </div>

                <h3 className="text-xl font-bold mb-6 text-gray-800">
                    {q.question || "Loading question..."}
                </h3>

                {q.type === 'mcq' ? (
                    <div className="space-y-3">
                        {q.options.map((opt, i) => (
                            <button
                                key={i}
                                onClick={() => handleAnswer(opt)}
                                className={`w-full p-4 rounded-xl border text-left
                          ${answers[currentQIndex] === opt
                                        ? 'border-indigo-600 bg-indigo-50 text-gray-900'
                                        : 'border-gray-200 text-gray-800 hover:bg-gray-50'}
                        `}
                            >
                                {opt}
                            </button>
                        ))}
                    </div>
                ) : (
                    <>
                        <pre className="bg-gray-900 text-gray-200 p-4 rounded-xl mb-4 font-mono text-sm">
                            {q.starterCode || '// Write your solution here'}
                        </pre>
                        <textarea
                            className="w-full h-48 border rounded-xl p-4 font-mono text-gray-800"
                            value={answers[currentQIndex] || ''}
                            onChange={e => handleAnswer(e.target.value)}
                            placeholder="Write your code here..."
                        />
                    </>
                )}

                <div className="mt-8 text-right">
                    <button
                        onClick={nextQuestion}
                        disabled={!answers[currentQIndex]}
                        className={`px-8 py-4 rounded-xl font-bold
              ${answers[currentQIndex]
                                ? 'bg-indigo-600 text-white'
                                : 'bg-gray-200 text-gray-400'
                            }`}
                    >
                        {currentQIndex === questions.length - 1 ? 'Finish' : 'Next'}
                        <ArrowRight className="inline ml-2" />
                    </button>
                </div>
            </div>
        </motion.div>
    );
};

export default SkillAssessment;