{{- range $name, $svc := .Values.services }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}-secrets
  namespace: {{ $.Values.global.namespace }}
spec:
  provider: {{ $.Values.global.secrets.provider }}
  parameters:
    vaultAddress: {{ $.Values.global.secrets.vaultAddress | quote }}
    roleName: {{ $name | quote }}
    objects: |
      - objectName: "hire1percent/{{ $name }}/MONGO_URI"
        secretKey: MONGO_URI
      - objectName: "hire1percent/{{ $name }}/SERVICE_TOKEN"
        secretKey: SERVICE_TOKEN
  secretObjects:
    - secretName: {{ $name }}-secrets
      type: Opaque
      data:
        - objectName: "hire1percent/{{ $name }}/MONGO_URI"
          key: MONGO_URI
        - objectName: "hire1percent/{{ $name }}/SERVICE_TOKEN"
          key: SERVICE_TOKEN
{{- end }}
