{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: hire1percent
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $svc.port }}
{{- end }}
